# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Play for setting up
  hosts: all
  become: true
  user: "{{ ansible_ssh_user }}"

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/handlers.yml

  vars:
    ssh_public_key: ~/.ssh/id_rsa.pub

  vars_prompt:
    - name: new_password
      prompt: "Enter new password"
      private: true

  tasks:
    - name: Create .ssh
      ansible.builtin.file:
        state: directory
        dest: "/home/{{ ansible_ssh_user }}/.ssh/"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "0700"


    - name: Push SSH key to the Raspberry Pi
      ansible.builtin.copy:
        src: "{{ ssh_public_key }}"
        dest: "/home/{{ ansible_ssh_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "0600"

    - name: Change default user password
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        append: true
        groups: adm, sudo
      # no_log: true

    - name: Expand filesystem
      ansible.builtin.command:
        "raspi-config --expand-rootfs"
      register: filesystem_expanded
      changed_when: filesystem_expanded.rc != 0
      become: true
      notify: reboot

    - name: Show IP Address
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
