---
- name: Setup MCP2515 can device
  lineinfile:
    dest=/boot/config.txt
    regexp='^dtoverlay=mcp2515-{{ mcp2515_overlay_can_device }}'
    line="dtoverlay=mcp2515-{{ mcp2515_overlay_can_device }},oscillator={{ mcp2515_oscillator_freq }},interrupt={{ mcp2515_int_pin }},cs2={{ mcp2515_cs2 }}"
  notify: reboot

- name: I2C kernel module needs to be loaded at boot time
  lineinfile:
    path: /etc/modules
    line: "i2c-dev"
    state: present
  notify: reboot

- name: Setup a CAN device
  template:
    src: can.j2
    dest: /etc/network/interfaces.d/{{ mcp2515_can_device }}
    mode: '0644'
  notify: reboot

- name: Install can-utils
  apt: pkg=can-utils state=latest
