- name: restart-udev
  service: name=udev state=restarted

- name: restart-networking
  service: name=networking state=restarted

- name: restart-rsyslog
  service: name=rsyslog state=restarted

- name: update_initramfs
  shell: if [ -f "/boot/initrd.img-$(uname -r)" ]; then update-initramfs -u -k $(uname -r); else update-initramfs -c -k $(uname -r); fi
  notify: reboot

- name: reload_sysctl
  shell: "sysctl -p"

# Keep this at the end to run the reboot handler after all other handlers
- name: reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami