---
- name: Configure the kernel to signal the Sailor Hat on power off
  lineinfile:
    path: /boot/config.txt
    line: "dtoverlay=gpio-poweroff,gpiopin=2,input,active_low=17"
    state: present
  notify: reboot

- name: Download sailor-hat-daemon
  git: repo=https://github.com/hatlabs/SH-RPi-daemon.git dest={{ sailor_hat_directory }} clone=yes force=yes
  become: false
  register: sailor_hat_sources

- name: Install overlays
  ansible.builtin.command: ./install.sh --enable RTC,CAN
  become: true
  when: sailor_hat_sources.changed
  notify: reboot